# Generated by Django 5.1.4 on 2025-01-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_category_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
